name: jrpn
description: Jovial RPN, a calculator simulator inspired by the HP-16C "Computer Scientist" Calculator

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.18+33    # See also lib/generic_main.dart

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  android_haptics:
    git:
      url: https://github.com/zathras/misc.git
      path: dart/android_haptics
      ref: master
  shared_preferences: ^2.3.4
  meta: ^1.15.0
  share_plus: ^11.0.0
  app_links: ^6.0.1
  archive: ^4.0.2
  url_launcher: ^6.0.3
  file_selector: ^1.0.0
  desktop_multi_window:
    git:
      url: https://github.com/zathras/tmp_desktop_multi_window.git
      path: packages/desktop_multi_window
      ref: main
  jovial_svg: ^1.0.24
  jovial_misc: ^0.9.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  test: ^1.16.5
  decimal: ^3.0.0
  vector_math: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/jupiter.si
    - assets/NAFO_OFAN_brain_damaged_cartoon_dogs.jpeg
    - assets/Тризуб.si
